DROP DATABASE IF EXISTS THUCTAP;
CREATE DATABASE THUCTAP;
USE THUCTAP;

DROP TABLE IF EXISTS COUNTRY;
CREATE TABLE COUNTRY(
country_id MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
country_name VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS Location;
CREATE TABLE Location(
Location_ID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
street_address VARCHAR(30) NOT NULL,
postal_code INT,
country_id MEDIUMINT UNSIGNED,
FOREIGN KEY (country_id) REFERENCES COUNTRY(country_id)
);

DROP TABLE IF EXISTS Employee;
CREATE TABLE Employee(
Employee_ID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
FULL_NAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
Location_ID MEDIUMINT UNSIGNED,
FOREIGN KEY (Location_ID) REFERENCES Location(Location_ID)
);


-- CAU 1
INSERT INTO COUNTRY (country_name)
VALUES ('VIET NAM'),
('HAN QUOC'),
('NHAT BAN');


INSERT INTO Location (street_address, postal_code,country_id)
VALUES ('HA NOI', 100000, 1),
('SEOUL', 100015, 2),
('TOKYO', 1000001, 3);

INSERT INTO Employee (FULL_NAME, EMAIL,Location_ID)
VALUES ('NGUYEN VAN A', 'NN03@GMAIL.COM', 1),
('TRAN VAN B', 'NN04@GMAIL.COM', 2),
('PHAM VAN C', 'NN05@GMAIL.COM', 3),
('NGUYEN 10VAN A', 'NN03@10GMAIL.COM', 2),
('NGUYE1N VAN A', 'NN01@GMAIL.COM', 2),
('NGU2YEN VAN A', 'NN023@GMAIL.COM', 2),
('NGUY3EN VAN A', 'N4N03@GMAIL.COM', 2),
('NGUYEN4 VAN A', 'NN03@G4MAIL.COM', 2),
('NGU5YEN VAN A', 'NN03@G5MAIL.COM', 2),
('NGUY6EN VAN A', 'NN036@GMAIL.COM', 2),
('NGUYEN7 VAN A', 'NN03@7GMAIL.COM', 2),
('NGUY8EN VAN A', 'NN03@8GMAIL.COM', 2);



-- CAU 2
SELECT * FROM Employee AS A
JOIN Location AS B ON A.Location_ID = B.Location_ID
JOIN COUNTRY AS C ON B.country_id = C.country_id
WHERE country_name = 'VIET NAM';

SELECT C.country_name FROM Employee AS A
JOIN Location AS B ON A.Location_ID = B.Location_ID
JOIN COUNTRY AS C ON B.country_id = C.country_id
WHERE A.EMAIL = 'NN03@GMAIL.COM';

SELECT C.country_name,B.street_address,COUNT(A.Location_ID) FROM Employee AS A
LEFT JOIN Location AS B ON A.Location_ID = B.Location_ID
JOIN COUNTRY AS C ON B.country_id = C.country_id
GROUP BY A.Location_ID;

-- CAU 3
DROP TRIGGER CAU3;
DELIMITER $$
CREATE TRIGGER CAU3
BEFORE INSERT ON Employee
FOR EACH ROW
BEGIN
DECLARE  v_countryid INT;
DECLARE  v_country INT;
SELECT country_id INTO  v_country FROM location WHERE neW.Location_ID = Location_ID;
SELECT count(A.country_id) into v_countryid from  location as a
RIGHT JOIN employee as b on a.location_id = b.Location_ID
WHERE v_country = A.country_id
GROUP BY A.country_id;
if v_countryid >= 10 then
SIGNAL SQLSTATE '12345'
SET MESSAGE_TEXT = 'QUOC GIA DA CO DU 10 Employee';
END IF;
END $$
DELIMITER ;


INSERT INTO `thuctap`.`Employee` (`Employee_ID`, `FULL_NAME`, `EMAIL`, `Location_ID`) VALUES ('13', 'TRAN VAN B', 'DGFGDFG', '2');


-- CAU 4
DROP TRIGGER CAU4;
DELIMITER $$
CREATE TRIGGER CAU4
BEFORE DELETE ON Location
FOR EACH ROW
BEGIN
 UPDATE Employee SET Location_ID = NULL WHERE (Location_ID= OLD.Location_ID);
END $$
DELIMITER ;

DELETE 
FROM LOCATION
WHERE LOCATION_ID = 2;

SELECT * FROM EMPLOYEE;









