DROP DATABASE IF EXISTS fresher;
CREATE DATABASE FRESHER;
USE FRESHER;
DROP TABLE IF EXISTS TRAINEE;
CREATE TABLE TRAINEE (
    TRAINEEID 	INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    FULLNAME	VARCHAR(50) NOT NULL,
    BIRTHDATE 	DATE NOT NULL,
    GENDER 		ENUM('MALE', 'FEMALE', 'UNKNOW'),
    ETIQ 		INT UNSIGNED CHECK (ETIQ >= 0 AND ETIQ <= 20),
    ETGMATH		INT UNSIGNED CHECK (ETGMATH >= 0 AND ETGMATH <= 20),
    ETENGLISH	INT UNSIGNED CHECK (ETENGLISH >= 0 AND ETENGLISH <= 20),
    TRAININGCLASS VARCHAR(50),
    EVALUATIONNOTES VARCHAR(50)
);

INSERT INTO TRAINEE (FULLNAME,BIRTHDATE, GENDER, ETIQ, ETGMATH, ETENGLISH, TRAININGCLASS, EVALUATIONNOTES)
VALUES ('NGUYEN VAN NAC','1997-02-17','MALE','7','6','14','VTI001','DHBKHN'),
('DANG THI THUY LINH','1996-04-27','FEMALE','18','16','19','VTI001','DHTL'),
('TRANVANNAC','1997-04-27','MALE','12','15','10','VTI001','DHBKHN'),
('HOANG THI THU NGA','1996-11-12','FEMALE','12','10','19','VTI001','DHQGHN'),
('NGUYEN QUANG HAI','1996-05-21','MALE','9','11','16','VTI001','DHTL'),
('HOANG MINH DUC','1995-02-26','MALE','9','8','9','VTI002','DHXD'),
('PHUNG QUOC TUAN','1997-01-27','MALE','16','14','15','VTI002','DHBKHN'),
('NGUYEN THI TU LINH','1997-08-08','FEMALE','15','16','14','VTI002','DHQGHN'),
('NGUYEN VAN DUNG','1995-10-09','MALE','8','8','19','VTI002','DHBKHN'),
('PHAM KHANH HUYEN','1997-01-12','FEMALE','16','17','16','VTI003','DHKTQD'),
('PHAM QUOC LONG','1994-07-05','MALE','9','8','12','VTI003','DHBKHN');

-- ('PHAM QUOC BAO','1994-04-18','MALE','15','18','30','VTI002','DHBKHN');

-- CAU 4
SELECT * FROM TRAINEE
WHERE ETIQ >= 12 AND ETGMATH >= 12 AND ETENGLISH >=12
ORDER BY BIRTHDATE;	

-- CAU 5
SELECT * FROM TRAINEE
WHERE FULLNAME LIKE ' % N%C';

-- CAU 6
SELECT * FROM TRAINEE
WHERE FULLNAME LIKE '% _G%';

-- CAU 7
SELECT * FROM TRAINEE
WHERE LENGTH(FULLNAME)= 10 AND FULLNAME LIKE '%C';

-- cau 8
SELECT DISTINCT FULLNAME FROM TRAINEE;

-- CAU 9
SELECT FULLNAME FROM TRAINEE
ORDER BY FULLNAME ASC;

-- CAU 10

SELECT * FROM TRAINEE
WHERE LENGTH(FULLNAME) = (SELECT MAX(LENGTH(FULLNAME)) FROM TRAINEE);

-- CAU 11
SELECT FULLNAME, TRAINEEID, BIRTHDATE  FROM TRAINEE
WHERE LENGTH(FULLNAME) = (SELECT MAX(LENGTH(FULLNAME)) FROM TRAINEE);

-- CAU 12
SELECT FULLNAME, ETIQ, ETGMATH, ETENGLISH  FROM TRAINEE
WHERE LENGTH(FULLNAME) = (SELECT MAX(LENGTH(FULLNAME)) FROM TRAINEE);

-- CAU 13
SELECT * FROM TRAINEE
ORDER BY BIRTHDATE DESC LIMIT 5;

-- CAU 14
SELECT * FROM TRAINEE
WHERE (ETIQ + ETGMATH) >=20 AND ETIQ >=8 AND ETGMATH >=8 AND ETENGLISH >=18;

-- CAU 15
DELETE
FROM TRAINEE
WHERE TRAINEEID = 5;

-- CAU 16
DELETE
FROM TRAINEE
WHERE ETIQ + ETGMATH <= 15;

-- CAU 17
DELETE
FROM trainee
WHERE year(curdate()) - year(BIRTHDATE) >30 ;


-- CAU 18
UPDATE TRAINEE
SET TRAININGCLASS = 'VTI003'
WHERE TRAINEEID = 3;

-- CAU 19
UPDATE TRAINEE
SET FULLNAME = 'LEVANA',
ETIQ= '10',
ETGMATH = '15',
ETENGLISH= '20'
WHERE TRAINEEID = 10;

-- CAU 20
SELECT count(TRAININGCLASS) FROM TRAINEE WHERE TRAININGCLASS = 'VTI001';


-- CAU 22
SELECT count(TRAININGCLASS) FROM TRAINEE 
WHERE TRAININGCLASS = 'VTI001' OR  TRAININGCLASS ='VTI003';


-- CAU 23
SELECT count(*) FROM TRAINEE
WHERE GENDER = 'MALE';

SELECT count(*) FROM TRAINEE
WHERE GENDER = 'FEMALE';

SELECT count(*) FROM TRAINEE
WHERE GENDER = 'UNKNOW';

-- CAU 24
SELECT TRAININGCLASS FROM TRAINEE
GROUP BY TRAININGCLASS HAVING COUNT(TRAININGCLASS) >= 5;

-- CAU 25
SELECT TRAININGCLASS FROM TRAINEE
GROUP BY TRAININGCLASS HAVING COUNT(TRAININGCLASS) >= 2;

-- CAU 26
SELECT EVALUATIONNOTES FROM TRAINEE
GROUP BY EVALUATIONNOTES HAVING COUNT(EVALUATIONNOTES) <= 4;

-- CAU 27
SELECT TRAINEEID, FULLNAME, TRAININGCLASS FROM TRAINEE
WHERE TRAININGCLASS = 'VTI001';

SELECT TRAINEEID, FULLNAME, TRAININGCLASS FROM TRAINEE
WHERE TRAININGCLASS = 'VTI002';

SELECT TRAINEEID, FULLNAME, TRAININGCLASS FROM TRAINEE
WHERE TRAININGCLASS = 'VTI001'
UNION
SELECT TRAINEEID, FULLNAME, TRAININGCLASS FROM TRAINEE
WHERE TRAININGCLASS = 'VTI002';




