DROP DATABASE IF EXISTS testing_system_assigment_1;
CREATE DATABASE testing_system_assigment_1;
USE testing_system_assigment_1;

DROP TABLE IF EXISTS Department;
CREATE TABLE Department(
DEPARTMENTID	MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
DEPARTMENTNAME	NVARCHAR(50) UNIQUE KEY NOT NULL
);
-- Create tale Position
DROP TABLE IF EXISTS `Position`;
CREATE TABLE `Position`(
PositionID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
PositionName NVARCHAR(50) UNIQUE KEY NOT NULL
);

-- CREATE TABLE ACCOUNT
DROP TABLE IF EXISTS `ACCOUNT`;
CREATE TABLE `ACCOUNT`(
ACCOUNTID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
EMAIL VARCHAR(100) UNIQUE KEY,
USERNAME NVARCHAR(50) NOT NULL,
FULLNAME NVARCHAR(50),
DEPARTMENTID MEDIUMINT UNSIGNED NOT NULL,
POSITIONID MEDIUMINT UNSIGNED NOT NULL ,
CREATEDATE DATETIME DEFAULT NOW(),
 FOREIGN KEY(DEPARTMENTID) REFERENCES Department(DEPARTMENTID),
 FOREIGN KEY(POSITIONID) REFERENCES `Position`(PositionID)
);

-- CREATE TABLE GROUP
DROP TABLE IF EXISTS `GROUP`;
CREATE TABLE `GROUP`(
GROUPID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
GROUPNAME NVARCHAR(20),
CREATORID MEDIUMINT UNSIGNED UNIQUE KEY NOT NULL,
CREATEDATE DATETIME DEFAULT NOW(),
FOREIGN KEY (CREATORID) REFERENCES `ACCOUNT`(ACCOUNTID)
);

-- CREATE TABLE GROUPACCOUNT
DROP TABLE IF EXISTS GROUPACCOUNT;
CREATE TABLE GROUPACCOUNT(
GROUPID MEDIUMINT UNSIGNED ,
ACCOUNTID MEDIUMINT UNSIGNED UNIQUE KEY NOT NULL,
JOINDATE DATETIME DEFAULT NOW(),
FOREIGN KEY (GROUPID) REFERENCES `GROUP` (GROUPID),
FOREIGN KEY (ACCOUNTID) REFERENCES `ACCOUNT`(ACCOUNTID)
);

-- CREATE TABLE TYPEQUESTION
DROP TABLE IF EXISTS TYPEQUESTION;
CREATE TABLE TYPEQUESTION (
TYPEID TINYINT AUTO_INCREMENT PRIMARY KEY,
TYPENAME ENUM('ESSAY','MULTIPLE-CHOICE') 
);

-- CREATE TABBLE CATEGORYQUESTION
DROP TABLE IF EXISTS CATEGORYQUESTION;
CREATE TABLE CATEGORYQUESTION(
CATEGORYID INT AUTO_INCREMENT PRIMARY KEY,
CATEGORYNAME ENUM('JAVA','.NET','SQL','POSTMAN','RUBY')
);

-- CREATE TABLE QUESTION
DROP TABLE IF EXISTS QUESTION;
CREATE TABLE QUESTION(
QUESTIONID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
CONTENT NVARCHAR(100),
CATEGORYID INT,
TYPEID TINYINT,
CREATORID INT,
CREATEDATE DATETIME DEFAULT NOW(),
FOREIGN KEY (TYPEID) REFERENCES TYPEQUESTION (TYPEID)
);

-- CREATE TABLE ANSWER
DROP TABLE IF EXISTS ANSWER;
CREATE TABLE ANSWER(
ANSWERID INT AUTO_INCREMENT PRIMARY KEY,
CONTENT NVARCHAR(100),
QUESTIONID MEDIUMINT UNSIGNED NOT NULL,
ISCORRECT BIT,
FOREIGN KEY (QUESTIONID) REFERENCES QUESTION(QUESTIONID)
);

-- CREATE TABLE EXAM
DROP TABLE IF EXISTS EXAM;
CREATE TABLE EXAM(
EXAMID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
`CODE` VARCHAR(50),
TITLE VARCHAR(50),
CATEGORYID INT,
DURATION TIME,
CREATORID INT DEFAULT (5),
CREATEDATE DATETIME DEFAULT NOW()
);

-- CREATE TABLE EXAMQUESTION
DROP TABLE IF EXISTS EXAMQUESTION;
CREATE TABLE EXAMQUESTION(
EXAMID MEDIUMINT UNSIGNED,
QUESTIONID MEDIUMINT UNSIGNED ,
FOREIGN KEY (QUESTIONID) REFERENCES QUESTION(QUESTIONID),
FOREIGN KEY (EXAMID) REFERENCES EXAM(EXAMID)
);


INSERT INTO Department (DEPARTMENTNAME)
VALUES ('TEST'),
('MKT'),
('BẢO VỆ'),
('NHÂN SỰ'),
('GIÁM ĐỐC'),
('KỸ THUẬT'),
('TÀI CHÍNH');

INSERT INTO `Position` (POSITIONNAME)
VALUES ('DEV'),
('TEST'),
('MKT'),
('GIÁM ĐỐC'),
('PM'),
('SCRUM MASTER');

INSERT INTO `ACCOUNT` (EMAIL, USERNAME, FULLNAME, DEPARTMENTID, POSITIONID)
VALUES ('HIEUPT87@GNAIL.COM','HIEUPT','PHAM TRUNG HIEU', 5, 4),
('HAINQ215@GMAIL.COM','HAINQ','NGUYEN QUANG HAI', 1, 2),
('THANHNB127@GMAIL.COM','THANHNB12','NGUYEN BA THANH',2 , 3),
('HUNGNT231@GMAIL.COM','HUNGNT23','NGUYEN THANH HUNG', 3,5),
('HUYNG045@GNAIL.COM','HUYNQ123','NGUYEN QUANG HUY', 4,5),
('DUNGVL123@GMAIL.COM','DUNGVL123','NGUYEN VAN DUNG', 6, 5),
('CUONGLM10101@GMAIL.COM','CUONGLM0101','LUU MANH CUONG', 7,5),
('LINHNV187@GMAIL.COM','LINHNV12','NGUYEN VAN LINH', 1,5);

-- 
INSERT INTO `GROUP` ( GROUPNAME, CREATORID)
VALUES 	('NHOM1', 1),
		('NHOM2', 2),
		('NHOM3',3),
        ('NHOM4',4);
        
INSERT INTO GROUPACCOUNT (GROUPID, ACCOUNTID)
VALUES (1, 1),
(1,5),
(2,2),
(2,6),
(3,3),
(3,7),
(4,4),
(4,8);

INSERT INTO TYPEQUESTION (TYPENAME)
VALUES ('ESSAY'),
('MULTIPLE-CHOICE');

INSERT INTO CATEGORYQUESTION (CATEGORYNAME)
VALUES ('JAVA'),
('.NET'),
('SQL'),
('POSTMAN'),
('RUBY');

INSERT INTO QUESTION (CONTENT, CATEGORYID, TYPEID, CREATORID)
VALUES ('ABC', 1, 1, 5),
('ABCD', 2, 1, 5),
('ABD', 3, 2, 5),
('BCD', 4, 1, 5),
('ADB', 5, 2, 5),
('BCD', 4, 1, 5),
('ÀGF', 1, 2, 5),
('QZS', 2, 2, 5),
('THS', 3, 1, 5),
('HGD', 5, 1, 5);

INSERT INTO ANSWER (CONTENT, QUESTIONID, ISCORRECT)
VALUES ('ABC', 1, 0),
('ABCD', 2, 1),
('ABD', 3, 0),
('BCD', 4, 1),
('ADB', 5, 1),
('BCD', 6, 1),
('ÀGF', 7, 0),
('QZS', 8, 1),
('THS', 9, 0),
('HGD', 10, 0);

INSERT INTO EXAM (`CODE`,TITLE, CATEGORYID, DURATION)
VALUES ('12A1','AAA', 1, '00:30:00'),
('12A2','BBB', 2, '01:10:00'),
('12A3','CCC', 3, '01:00:00'),
('12A4','DDD', 4, '00:45:00'),
('12A5','EEE', 5, '00:40:00');

INSERT INTO EXAMQUESTION (EXAMID, QUESTIONID)
VALUES (1,1),
(1,7),
(2,2),
(2,8),
(3,3),
(3,9),
(4,4),
(4,10),
(5,5),
(5,6);


------------------------------ 

UPDATE DEPARTMENT
SET DEPARTMENTNAME = ' MKT3'
WHERE DEPARTMENTID = 2


